name: Infrastructure and dbt CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  terraform:
    name: Terraform checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (dev)
        run: terraform -chdir=infra/terraform/dev init -backend=false

      - name: Terraform validate (dev)
        run: terraform -chdir=infra/terraform/dev validate

      - name: Terraform init (operations example)
        run: terraform -chdir=modules/operations/examples/basic init -backend=false

      - name: Terraform plan (operations example)
        run: terraform -chdir=modules/operations/examples/basic plan -lock=false -input=false

  dbt:
    name: dbt compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt/dpc_learning

    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}/dbt/dpc_learning
      DBT_RS_WORKGROUP: placeholder
      DBT_RS_REGION: ap-northeast-1
      DBT_RS_DATABASE: dpc_learning
      DBT_RS_SECRET_ARN: arn:aws:secretsmanager:ap-northeast-1:000000000000:secret:placeholder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt dependencies
        run: pip install -r requirements.txt

      - name: dbt deps
        run: dbt deps

      - name: dbt compile
        run: dbt compile
